# Generated by Django 4.0.4 on 2022-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderequest',
            name='userid',
        ),
        migrations.AddField(
            model_name='coderequest',
            name='username',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
