# Generated by Django 4.0.4 on 2022-09-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_newlotteries_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=100)),
                ('number', models.IntegerField(max_length=100)),
                ('period', models.IntegerField(max_length=100)),
                ('better', models.IntegerField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
