# Generated by Django 4.0.4 on 2022-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0005_betsingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='betsingle',
            name='evenorodd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='betsingle',
            name='number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
