# Generated by Django 4.0.4 on 2022-09-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0006_betsingle_evenorodd_alter_betsingle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='userid',
        ),
        migrations.AddField(
            model_name='wallet',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
