# Generated by Django 4.0.4 on 2022-09-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0007_remove_wallet_userid_wallet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sponsor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
