# Generated by Django 4.0.4 on 2022-10-05 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0008_alter_member_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='newlotteriesthreem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default='open', max_length=50)),
            ],
        ),
    ]
