# Generated by Django 4.0.4 on 2022-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0009_newlotteriesthreem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlotteries',
            name='timing',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlotteriesthreem',
            name='timing',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
