# Generated by Django 4.0.4 on 2022-10-05 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0011_betsingle_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultthreem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result', models.IntegerField(verbose_name=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
