# Generated by Django 4.0.4 on 2022-10-05 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0012_resultthreem'),
    ]

    operations = [
        migrations.CreateModel(
            name='newlotteriesnine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default='open', max_length=50)),
                ('timing', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultnine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result', models.IntegerField(verbose_name=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
