# Generated by Django 4.0.4 on 2022-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0013_newlotteriesnine_resultnine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlotteries',
            name='created_by',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='newlotteriesnine',
            name='created_by',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='newlotteriesthreem',
            name='created_by',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultnine',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultnine',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultthreem',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultthreem',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
