# Generated by Django 4.0.4 on 2022-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0016_betsingle_winnningamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlotteries',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlotteriesnine',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newlotteriesthreem',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
