# Generated by Django 4.0.4 on 2022-10-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0018_result_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultnine',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultthreem',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
